# Autogenerated by devscripts/update-version.py

__version__ = '2024.08.05.112038'

RELEASE_GIT_HEAD = '90ad90a888ba720ef03ef2319f23dc4e2e4a4dc5'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'haccy/yt-dlp'

ORIGIN = 'haccy/yt-dlp'

_pkg_version = '2024.08.05.112038'
