# Autogenerated by devscripts/update-version.py

__version__ = '2025.01.31.112106'

RELEASE_GIT_HEAD = 'cbc8513c1cf615f059f9ab5b25adae538582220d'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'haccy/yt-dlp'

ORIGIN = 'haccy/yt-dlp'

_pkg_version = '2025.01.31.112106'
