# Autogenerated by devscripts/update-version.py

__version__ = '2024.10.24.112154'

RELEASE_GIT_HEAD = '02ac6ab80e66fba43c448a262e2931afb47a16d2'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'haccy/yt-dlp'

ORIGIN = 'haccy/yt-dlp'

_pkg_version = '2024.10.24.112154'
