name: Rebase on Upstream

on:
  workflow_dispatch:    # run manually

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        ref: work
        fetch-depth: 0
    - uses: imba-tjd/rebase-upstream-action@master
      with:
        branch: master
        depth: 0
